language: php

php:
  - 5.3
  - 5.4

before_script:
  - composer install --dev
  - git clone git://github.com/opensky/Symfony2-coding-standard.git vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/Symfony2/

script: phpunit -c app
