---
language: php

php:
    - 5.3
    - 5.4

env:
    global:
        # Flickr API key
        - secure: "EfOsa/Vt1c2Sqwm2VmsZMIeYMTZKwIgndDr0FhyxGna8m50nXPHDSrJsDv3P\n7zBtz5224R5GgNHouiV4imCuboTnOrJ3uTPAGj0iNrNVAGQn4l4mQe9dgkd2\nig6n4RPlhBG7CvaaLl3PJS+dT7gXfPUOE9dAfydXwmdQFDQRKsc="
        # Yahoo API key
        - secure: "SHFXCf3NBp89OHucvY8HOx0xUFwkpXh262+YhE/hjb06O5dM1/GZf6euM6Ua\nePtGzSe3INqaSaZJmEPdw8yVaAU9ufSGe9PvGdYzRNwkT/8D0/c9JcNsBA/I\n0rpJpjQKvIm4JA7EzTospWf1U0pU/Am5I4PgINYNobfO0akRhUw="

before_script:
    - mv app/config/parameters.yml{.dist,}
    - sed -i "s/{{yahoo_api_key}}/$YAHOO_API_KEY/" app/config/parameters.yml
    - sed -i "s/{{flickr_api_key}}/$FLICKR_API_KEY/" app/config/parameters.yml
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev --no-interaction
    - git clone git://github.com/opensky/Symfony2-coding-standard.git vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/Symfony2/

script: phpunit -c app && vendor/bin/phpcs --standard=Symfony2 src/Tasuk/GuessWhereBundle/
